# Generated by Django 5.1.3 on 2025-01-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='school_class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.profile'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school_class_students',
            field=models.ManyToManyField(to='core.student'),
        ),
    ]
