# Generated by Django 5.1.3 on 2025-01-28 12:32

import django.db.models.deletion
import employee.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=244)),
                ('book_picture', models.ImageField(upload_to=employee.models.bookpath)),
                ('book_publisher', models.CharField(max_length=244)),
                ('book_edition_number', models.IntegerField()),
                ('book_pnld_code', models.CharField(max_length=50)),
                ('book_description', models.TextField()),
                ('book_number_pages', models.IntegerField()),
                ('number_in_stock', models.IntegerField()),
                ('number_available', models.IntegerField()),
                ('book_status', models.IntegerField(choices=[(1, 'Disponível'), (2, 'Indisponível')])),
                ('book_author', models.ManyToManyField(to='employee.author')),
                ('book_genre', models.ManyToManyField(to='employee.genre')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_book_number', models.IntegerField()),
                ('borrow_receipt_date', models.DateField()),
                ('borrow_delivery_date', models.DateField()),
                ('borrow_status', models.IntegerField(choices=[(1, 'analise'), (2, 'aberto'), (3, 'pendente'), (4, 'fechado')], default=1)),
                ('borrow_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
                ('borrow_schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_student_receipt_date', models.DateField()),
                ('borrow_student_delivery_date', models.DateField(blank=True, null=True)),
                ('borrow_student_status', models.IntegerField(choices=[(1, 'Em espera'), (2, 'Emprestado'), (3, 'Devolvido'), (4, 'Atrasado'), (5, 'Devolvido com atraso')])),
                ('borrow_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.borrow')),
                ('borrow_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=244)),
                ('profile_registration', models.CharField(max_length=14)),
                ('profile_type', models.IntegerField(choices=[(1, 'Employer'), (2, 'Teacher')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.profile'),
        ),
    ]
