# Generated by Django 5.1.3 on 2025-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowstudent',
            name='borrow_student_receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
