# Generated by Django 5.1.3 on 2025-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_borrowstudent_borrow_student_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowstudent',
            name='borrow_student_status',
            field=models.IntegerField(choices=[(1, 'Em espera'), (2, 'Emprestado'), (3, 'Devolvido'), (4, 'Atrasado'), (5, 'Devolvido com atraso'), (6, 'não recebeu')]),
        ),
    ]
